# Generated by Django 4.1.7 on 2023-04-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={
                "db_table": "admins_category",
                "ordering": ["name", "date_created", "date_updated"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True, null=True)),
                ("code", models.IntegerField(unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.category",
                    ),
                ),
            ],
            options={
                "db_table": "admins_subject",
                "ordering": ["name", "date_created", "date_updated"],
                "abstract": False,
            },
        ),
    ]
