# Generated by Django 4.2 on 2023-04-24 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z- A-z]+$",
                        code="Invalid name",
                        message="Invalide data to the fields........",
                    )
                ],
            ),
        ),
    ]
